version: "3.7"
services:
  api-user:
    image: openemp/user-api:latest
    environment:
      spring_profiles_active: dev
    networks:
      openemp:
        aliases:
          - user-api
  ui-core:
    image: openemp/core-ui:latest
    networks:
      openemp:
        aliases:
          - core-ui
  ui-root:
    image: openemp/root-ui:latest
    networks:
      openemp:
        aliases:
          - root-ui
    volumes:
      - "./proxy/confs/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
      - "443:80"
  ui-style:
    image: openemp/style-ui:latest
    volumes:
      - "./proxy/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      openemp:
        aliases:
          - style-ui
  ui-login:
    image: openemp/login-ui:latest
    volumes:
      - "./proxy/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      openemp:
        aliases:
          - login-ui
  ui-drawer:
    image: openemp/drawer-ui:latest
    networks:
      openemp:
        aliases:
          - drawer-ui
  ui-navbar:
    image: openemp/navbar-ui:latest
    networks:
      openemp:
        aliases:
          - navbar-ui
networks:
  openemp:
