---
- name: Prepare project directory
  file:
    state: absent
    path: ~/openemp

- name: Create project directory
  file:
    state: directory
    path: ~/openemp

- name: Checkout git repositroy
  ansible.builtin.git:
    repo: https://github.com/openemp/openemp-docker-compose.git
    dest: ~/openemp
    force: yes
