---
- name: Prepare project directory
  file:
    state: absent
    path: /home/{{ deploy_user }}

- name: Checkout git repositroy
  ansible.builtin.git:
    repo: https://github.com/openemp/openemp-docker-compose.git
    dest: /home/{{ deploy_user }}/openemp
    force: yes
 