---
- name: Ensure services are down
  ansible.builtin.command:
    cmd: docker-compose -p emp down -v
    chdir: ~/openemp

- name: Pull latest images
  ansible.builtin.command:
    cmd: docker-compose -p emp pull
    chdir: ~/openemp

- name: Start services
  ansible.builtin.command:
    cmd: docker-compose -p emp up -d
    chdir: ~/openemp
