name: Deploy to GCE VM

on: [ push ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run Ansible jobs
        uses: saubermacherag/ansible-playbook-docker-action@v1.4
        with:
          playbookName: './github/playbook/playbook.yml'
          inventoryFile: './github/playbook/inventory/sample/hosts.yml'
          extraVars: "-e vm_ip=${{ secrets.GCP_VM_IP }} -e vm_user=${{ secrets.GCP_VM_USER }} -e deploy_user=${{ secrets.GCP_DEPLOY_USER }}"
          verbosity: "vv"