name: Deploy to GCE VM

on: [ push ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run Ansible
        run: ansible-playbook .github/playbook.yml -i .github/inventory/sample/hosts.yml --extra-vars "vm_ip=${{ secrets.GCP_VM_IP }} vm_user=${{ secrets.GCP_VM_USER }} deploy_user=${{ secrets.GCP_DEPLOY_USER }}"
